spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka

server:
  port: 5002

# 日志
logging:
  level:
    cn:
      com:
        scitc:
          FeignGirlService: debug
# 数据压缩 提高传输效率
feign:
  compression:
    request:
      enabled: true
      mime-types: text/html,application/json
      min-request-size: 2048
    response:
      enabled: true
# 请求重试

provider:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: false
