spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug
